# Generated by Django 6.0.3 on 2026-03-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
