# Generated by Django 6.0.3 on 2026-03-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0002_alter_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
